baseURL: https://pratik-kanthi.github.io
languageCode: en-us
title: pratik kanthi
theme: PaperMod
params:
    defaultTheme: dark
    homeInfoParams:
        Title:  Welcome to this blog
        Content: Hi, this is Pratik.
    socialIcons:
      - name: "twitter"
        title: "<custom title>"
        url: "https://twitter.com"
      - name: "github"
        title: "<custom title>"
        url: "https://twitter.com"
      - name: "linkedin"
        title: "<custom title>"
        url: "https://twitter.com"
      - name: "cv"
        title: "<custom title>"
        url: "https://twitter.com"
      
languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
          - name: Archive
            url: archives
            weight: 5
          - name: Search
            url: search/
            weight: 10
          - name: Tags
            url: tags/
            weight: 10
          - name: Experiments
            url: experiments/
            weight: 1
        